-- Clear legacy non-Plaid merchant logos generated by logo.dev.
-- Keep merchantLogo only for values sourced from Plaid logo_url.
UPDATE "PlaidTransactionCache"
SET "merchantLogo" = NULL
WHERE "merchantLogo" IS NOT NULL
  AND (
    "merchantLogo" LIKE '%img.logo.dev/%'
    OR "merchantLogo" LIKE '%logo.dev/%'
  );
